In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine
import altair as alt
import numpy as np
from dotenv import load_dotenv
import umap
import re


print("All imports successful")

C:\Users\ckart\miniconda3\envs\dsenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

All imports successful

In [2]:
load_dotenv()

host = os.getenv("MYSQL_HOST", "localhost")
port = os.getenv("MYSQL_PORT", "3306")
user = os.getenv("MYSQL_USER","root")
password = os.getenv("MYSQL_PSWD","2316")
db = os.getenv("MYSQL_DB", "rxnorm")

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}?charset=utf8mb4"
)

In [24]:
from sqlalchemy import text

def Searchbar(term):
    sql = text("""
        SELECT RXCUI, SAB, TTY, STR
        FROM RXNCONSO
        WHERE STR LIKE :term
        AND TTY = 'DP'
    """)

    with engine.connect() as conn:
        result = pd.read_sql(sql, conn, params={'term': f'%{term}%'})

    if result.empty:
        raise ValueError("No matching drug found.")

    result["Extracted_Name"] = result["STR"].str.extract(r'\[(.*?)\]')

    ID = result.loc[0, "RXCUI"]
    Name = result.loc[0, "Extracted_Name"]

    return ID, Name

ID, Name = Searchbar("Tylenol PM")
print(ID)
print(Name)

1092378
Tylenol PM Extra Strength

In [4]:
def Fetch_Drug_Form(drug_id):
    query = text("""
        SELECT DISTINCT
            r.RXCUI2 AS Drug_Form_ID, 
            r.RELA AS Relation, 
            c.STR AS Drug_Form
        FROM RXNCONSO c
        JOIN RXNREL r ON c.RXCUI = r.RXCUI2
        WHERE r.RXCUI1 = :drug_id 
          AND c.TTY = 'DP'
    """)

    with engine.connect() as conn:
        result = pd.read_sql(query, conn, params={"drug_id": drug_id})

    # Create Product_Name first
    result["Product_Name"] = result["Drug_Form"].str.extract(r'\[(.*?)\]')
    result["Product_Name"] = result["Product_Name"].fillna(result["Drug_Form"])

    # Case-insensitive dedup
    result = (
        result.assign(Product_Name_lower=result["Product_Name"].str.lower())
              .drop_duplicates(subset="Product_Name_lower")
              .drop(columns="Product_Name_lower")
    )

    return result

Fetch_Drug_Form(ID)

,Drug_Form_ID,Relation,Drug_Form,Product_Name
0,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET,ACETAMINOPHEN 325 mg ORAL TABLET
1,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Acetaminophe...,Acetaminophen 325 mg Round
2,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Regular Stre...,Regular Strength Pain Relief
3,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Clear Choice...,Clear Choice Regular Strength Pain Reliever
4,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Pain Relief ...,Pain Relief Regular Strength
5,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Aurophen Reg...,Aurophen Regular Strength
6,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Pain Relief ...,"Pain Relief Regular Strength, Aspirin Free"
7,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Acetaminophe...,Acetaminophen Regular Strength
8,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED ...",Direct Safety Aspirin Free
9,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [good sense p...,good sense pain relief
10,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED ...",Moore Medical Non Aspirin
11,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED ...",MEDIQUE APAP
12,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED ...",Henry Schein Acetaminophen
13,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [Dr S...",Dr Simi Pain Relief
14,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED","ACETAMINOPHEN 325 mg ORAL TABLET, COATED"
15,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [CareALL Acet...,CareALL Acetaminophen
16,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Pain Relief],Pain Relief
17,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL Tablet [ACETAMINOPHEN],ACETAMINOPHEN
18,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED","ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED"
20,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED ...",DRX CHOICE Regular Strength
21,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [ACETAMINOPHE...,ACETAMINOPHEN 325 MG
22,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [equate pain ...,equate pain reliever
23,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Medline],Medline
24,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [AMAZON BASIC...,AMAZON BASIC CARE ACETAMINOPHEN
25,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Regular Stre...,Regular Strength Acetaminophen
27,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [Medi...",Medi-First Plus Non-Aspirin
28,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [Medi...",Medi-First Non-Aspirin
29,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [MEDI...",MEDI FIRST PLUS Non-Aspirin
30,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [Dove...",Dover Aminofen
31,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [DOVE...",DOVER AMINOPHEN
32,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Acetaminophe...,Acetaminophen 325mg RS
33,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, FILM COATED ...",Regular Strength Pain Reliever
34,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Pain Reliever],Pain Reliever
37,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Rugby Regula...,Rugby Regular Strength Acetaminophen
38,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [basic care a...,basic care acetaminophen
40,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [Medi...",Medique at Home APAP
41,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [McKe...",McKesson Acetaminophen 325
42,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [Aphen],Aphen
43,313782,has_tradename,ACETAMINOPHEN 325 mg ORAL TABLET [dg health pa...,dg health pain relief
44,313782,has_tradename,"ACETAMINOPHEN 325 mg ORAL TABLET, COATED [Trav...",Travel Savvy Non-Aspirin

In [25]:
def Show_Ingredients(ID):
    query = f"""
    SELECT r.RXCUI2 as Ingredient_ID,r.RELA as Relation,c.STR as Ingredient
    from RXNCONSO c
    JOIN RXNREL r
    ON c.RXCUI = r.RXCUI2
    WHERE r.RXCUI1 = "{ID}" and c.TTY = "SCDC"
    GROUP by Ingredient_ID,Relation,Ingredient;
    """
    result1 = pd.read_sql(query, engine)
    return result1

df = Show_Ingredients(ID)
print(df)
ingredients = list(df["Ingredient_ID"])
ingredients

  Ingredient_ID     Relation                           Ingredient
0        315266  constitutes                 acetaminophen 500 MG
1        901813  constitutes  diphenhydramine hydrochloride 25 MG

['315266', '901813']

In [26]:
def Dose_Form(ID):
    query = f"""
    SELECT r.RXCUI2 as Ingredient_ID,r.RELA as Relation,c.STR as Ingredient
    from RXNCONSO c
    JOIN RXNREL r
    ON c.RXCUI = r.RXCUI2
    WHERE r.RXCUI1 = "{ID}" and c.TTY = "DF"
    GROUP by Ingredient_ID,Relation,Ingredient;
    """
    result = pd.read_sql(query, engine)
    DF = result["Ingredient"][0]
    return DF
Dose_Form(ID)

'Oral Tablet'

In [28]:
def get_generic(ID):
    query = f"""
    SELECT r.RXCUI2 as Ingredient_ID,c.STR as Ingredient
    from RXNCONSO c
    JOIN RXNREL r
    ON c.RXCUI = r.RXCUI2
    WHERE r.RXCUI1 = "{ID}" and c.TTY = "SCD"
    GROUP by Ingredient_ID,Ingredient;
    """
    res = pd.read_sql(query, engine)
    return res
    
get_generic(ID)

  Ingredient_ID                                         Ingredient
0       1092189  acetaminophen 500 MG / diphenhydramine hydroch...

In [29]:
def Exact_drugs(Ing_lst,ID):
    s = ""
    for i,j in enumerate(Ing_lst):
        if i == (len(Ing_lst) - 1):
            s+="r1.RXCUI1 = "+j
        else:
            s+="r1.RXCUI1 = "+j+" or "
            
    query = f"""
    WITH base AS (
        SELECT r2.RXCUI as ID, r2.STR as DP, r1.RXCUI1 as Ingredient_ID
        FROM RXNREL r1
        JOIN RXNCONSO r2
        ON r1.RXCUI2 = r2.RXCUI
        WHERE ({s}) and r2.TTY = "DP"
    ),
    keys_all AS (
        SELECT ID
        FROM base
        GROUP by ID
        HAVING COUNT(DISTINCT Ingredient_ID) = {len(Ing_lst)}
    )
    SELECT b.ID,b.DP
    FROM base b
    JOIN keys_all k
    ON b.ID = k.ID
    GROUP BY b.ID, b.DP
    """
    
    res = pd.read_sql(query, engine)
    dp = res["DP"].astype("string")

    has_bracket = dp.str.contains(r"\[", na=False)
    
    res["Product_Name"] = np.where(
        has_bracket,
        dp.str.rsplit("[", n=1).str[-1].str.rstrip("]"),
        "Generic"
    )
    
    keep_mask = (
        has_bracket
        & ~res["Product_Name"].str.lower().duplicated(keep="first")
    )
    
    res = res.loc[keep_mask].reset_index(drop=True)
    return res

In [30]:
def Union_Drugs(Ing_lst,ID):
    s = ""
    for i,j in enumerate(Ing_lst):
        if i == (len(Ing_lst) - 1):
            s+="r1.RXCUI1 = "+j
        else:
            s+="r1.RXCUI1 = "+j+" or "
            
    query = f"""
    WITH base AS (
        SELECT r2.RXCUI as ID, r2.STR as DP, r1.RXCUI1 as Ingredient_ID
        FROM RXNREL r1
        JOIN RXNCONSO r2
        ON r1.RXCUI2 = r2.RXCUI
        WHERE ({s}) and r2.TTY = "DP"
    ),
    keys_all AS (
        SELECT ID
        FROM base
        GROUP by ID
        HAVING COUNT(DISTINCT Ingredient_ID) < {len(Ing_lst)}
    )
    SELECT b.ID,b.DP
    FROM base b
    JOIN keys_all k
    ON b.ID = k.ID
    WHERE b.Id != {ID}
    GROUP BY b.ID, b.DP
    """
    
    res = pd.read_sql(query, engine)

    dp = res["DP"].astype("string")
    has_bracket = dp.str.contains(r"\[", na=False)
    res["Product_Name"] = np.where(
        has_bracket,
        dp.str.rsplit("[", n=1).str[-1].str.rstrip("]"),
        "Generic"
    )
    
    res = res.loc[has_bracket].copy()
    res = res.loc[~res["Product_Name"].str.lower().duplicated(keep="first")]
    res = res.drop_duplicates(subset="ID", keep="first").reset_index(drop=True)
    return res

In [31]:
def Ing_count(ID):
    query = f"""
    SELECT count(c.STR) as Count
    FROM RXNCONSO c
    JOIN RXNREL r
        ON c.RXCUI = r.RXCUI2
    WHERE r.RXCUI1 = "{ID}"
      AND c.TTY = "SCDC";
    """
    df = pd.read_sql(query, engine)
    return int(df["Count"][0])

In [32]:
def Ing_count_bulk(ids):
    if not ids:
        return {}

    ids = [str(i) for i in ids]
    placeholders = ", ".join([f":id{i}" for i in range(len(ids))])
    params = {f"id{i}": ids[i] for i in range(len(ids))}

    sql = text(f"""
        SELECT r.RXCUI1 AS ID, COUNT(DISTINCT c.STR) AS Count
        FROM RXNREL r
        JOIN RXNCONSO c ON c.RXCUI = r.RXCUI2
        WHERE r.RXCUI1 IN ({placeholders})
          AND c.TTY = 'SCDC'
        GROUP BY r.RXCUI1
    """)

    df = pd.read_sql(sql, engine, params=params)
    return dict(zip(df["ID"].astype(str), df["Count"].astype(int)))

In [33]:
def Fetch_Matches(exact_df, union_df, ID):
    target_count = Ing_count(ID)

    unique_ids = exact_df["ID"].dropna().astype(str).unique().tolist()
    count_map = Ing_count_bulk(unique_ids) 

    mask = exact_df["ID"].astype(str).map(count_map).eq(target_count)

    union_df = pd.concat([union_df, exact_df.loc[~mask]], ignore_index=True)
    exact_df = exact_df.loc[mask].copy()

    return exact_df, union_df

In [37]:
exact_df = Exact_drugs(ingredients, ID)
union_df = Union_Drugs(ingredients, ID)
df1, df2 = Fetch_Matches(exact_df,union_df,ID)
print(len(df1))
print(len(df2))

43
52

In [35]:
df1

,ID,DP,Product_Name
0,1094718,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,PANADOL PM
1,1117245,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,PAIN RELIEVER PM Extra Strength
2,1092378,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Tylenol PM Extra Strength
3,1092378,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Tylenol PM
4,1092378,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / ACETAMIN...,"Tylenol PM Extra Strength, CVP HEALTH"
5,1092378,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / ACETAMIN...,Lil Drug Store Tylenol PM Extra Strength
6,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,EXTRA STRENGTH PAIN RELIEF PM
7,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Pain Relief PM Extra Strength
8,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,CareOne Acetaminophen PM
9,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Acetaminophen PM Extra Strength
10,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Pain Relief Acetaminophen PM Extra Strength
11,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,good sense pain relief pm extra strength
12,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Topcare pain relief PM extra strength non habi...
13,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,dg health pain relief pm extra strength
14,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Dr Simi Pain Reliever PM
15,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Goodmeds Extra Strength Pain Relief PM
16,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Cystex PM
17,1092189,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / ACETAMIN...,"Pain Reliever PM, Extra Strength, 24-7 Life by..."
18,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Pain Relief PM
19,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Extra Strength Acetaminophen PM
20,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,meijer EXTRA STRENGTH Pain Relief PM CAPLET
21,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Acetaminophen PM
22,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,RIGHT REMEDIES EXTRA STRENGTH Pain Relief PM C...
23,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,GOOD REMEDIES Extra Strength Pain Relief PM Ca...
24,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Pain Reliever PM
25,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Kroger EXTRA STRENGTH Acetaminophen PM Caplet
26,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,NOTTS - Pain Relief PM
27,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Extra Strength Pain Reliever PM
28,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,ValuMeds Pain Relief PM Pain Reliever and Nigh...
29,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Extra Strength PM Pain Medicine
30,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,CAREALL Pain Relief PM Extra Strength
31,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Extra Strength Night Time Pain Medicine
32,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,RIGHT REMEDIES EXTRA STRENGTH PM Pain Relief
33,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Pain Reliever and Sleep Aid
34,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Extra Strength Night Time Pain Relief
35,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Extra Strength Nite-Time Pain Relief
36,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Genexa Acetaminophen PM Extra Strength
37,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Pain Relief Acetaminophen PM
38,1092189,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / ACETAMIN...,Extra Strength NiteTime Pain Relief
39,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,basic care acetaminophen pm
40,1092189,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / ACETAMIN...,Vicks ZzzQuil Night Pain
41,1092189,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / ACETAMIN...,CounterAct PM
42,1092189,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,CAREALL Non-Aspirin PM Extra Strength

In [36]:
df2

,ID,DP,Product_Name
0,1358835,ACETAMINOPHEN 500 mg ORAL TABLET [CETAFEN EXTRA],CETAFEN EXTRA
1,404172,ACETAMINOPHEN 500 mg / CAFFEINE 65 mg ORAL TAB...,Excedrin Tension Headache
2,1052641,ACETAMINOPHEN 500 mg / PAMABROM 25 mg / PYRILA...,Premsyn pms Premenstrual Pain Relief
3,1092416,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,Nytol
4,1089968,ACETAMINOPHEN 500 mg / CHLORPHENIRAMINE MALEAT...,Extra Strength TYLENOL Cold plus Flu Multi-Act...
5,901814,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / IBUPROFE...,ADVIL PM
6,1049909,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL CAPSU...,NIGHTTIME SLEEP AID
7,200977,"ACETAMINOPHEN 500 mg ORAL TABLET, FILM COATED ...",PANADOL Extra Strength
8,1297947,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE CITRATE...,GOODYS PM
9,1437725,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,Wal-Som
10,1550963,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / NAPROXEN...,Aleve PM
11,1919073,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL CAPSU...,Dormin
12,2360605,ASPIRIN 500 mg / ACETAMINOPHEN 500 mg / CAFFEI...,BC MAX
13,1093102,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,Unisom SleepMelts Nighttime Sleep-Aid
14,1052637,ACETAMINOPHEN 500 mg / PAMABROM 25 mg / PYRILA...,menstrual pain relief maximum strength
15,1099872,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE CITRATE...,Assured Headache PM (Aspirin Free)
16,307686,ACETAMINOPHEN 500 mg / CAFFEINE 65 mg ORAL TAB...,Tension Headache
17,2374361,ACETAMINOPHEN 500 mg in 0.95 g ORAL POWDER [TY...,TYLENOL Extra Strength
18,209459,ACETAMINOPHEN 500 mg ORAL TABLET [Tylenol Extr...,Tylenol Extra Strength Caplet
19,1092466,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,Simply Sleep
20,1648369,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL CAPSU...,Unisom SleepMinis Nighttime Sleep-Aid
21,1597298,ACETAMINOPHEN 500 mg / CAFFEINE 60 mg / PYRILA...,Buscapina
22,1189316,ACETAMINOPHEN 500 mg / DEXTROMETHORPHAN HYDROB...,DG HEALTH MULTI SYMPTOM SEVERE COLD
23,2046528,"DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL BAR, ...",Adult Allergy Relief
24,1550968,ACETAMINOPHEN 500 mg / DEXTROMETHORPHAN HYDROB...,SEVERE COLD plus FLU DAYTIME
25,1248360,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL CAPSU...,ZzzQuil Nighttime Sleep-Aid
26,1659960,ACETAMINOPHEN 650 mg / DIPHENHYDRAMINE HYDROCH...,nighttime severe cold and cough
27,1926221,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / PHENYLEP...,Benadryl Allergy Plus Congestion
28,198440,ACETAMINOPHEN 500 mg ORAL TABLET [VALUMEDS EXT...,VALUMEDS EXTRA STRENGTH PAIN RELIEF
29,1092421,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,Banophen
30,247324,DEXTROMETHORPHAN HYDROBROMIDE 15 mg / ACETAMIN...,EXTRA STRENGTH TYLENOL SEVERE COUGH PLUS SORE ...
31,1293942,ACETAMINOPHEN 500 mg ORAL TABLET [Pharbetol],Pharbetol
32,1053852,PYRILAMINE MALEATE 15 mg / PAMABROM 25 mg / AC...,Pamprin Multi-Symptom Maximum Strength
33,1049910,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL CAPSU...,Benadryl Allergy Liqui-Gels
34,1086986,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,Sominex
35,198439,"ACETAMINOPHEN 500 mg ORAL CAPSULE, COATED [Rap...",Rapidol
36,1049630,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,VALUMEDS ALLERGY RELIEF
37,1098496,ACETAMINOPHEN 500 mg / CHLORPHENIRAMINE MALEAT...,Coricidin HBP Night
38,1101534,ACETAMINOPHEN 500 mg / PHENYLEPHRINE HYDROCHLO...,Green Guard Advanced Sinus Relief
39,1250743,DEXTROMETHORPHAN HYDROBROMIDE 15 mg / ACETAMIN...,Extra Strength TYLENOL Cold Plus Flu Multi-Act...
40,209443,"ACETAMINOPHEN 500 mg ORAL TABLET, FILM COATED ...",Extra Strength Mapap
41,1052928,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / PHENYLEP...,Allergy Plus Congestion Relief
42,1052679,PHENYLEPHRINE HYDROCHLORIDE 5 mg / ACETAMINOPH...,CONTAC Cold Flu Night
43,1798453,ACETAMINOPHEN 500 mg / DEXBROMPHENIRAMINE MALE...,Biogesic
44,2670677,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / ACETAMIN...,Vicks NyQuil HOT REMEDY Cold and Flu
45,209890,ACETAMINOPHEN 500 mg ORAL CAPSULE [MAPAP Extra...,MAPAP Extra Strength
46,1046751,ACETAMINOPHEN 325 mg / DIPHENHYDRAMINE HYDROCH...,Severe Allergy Plus Sinus Headache
47,1872075,ACETAMINOPHEN 500 mg / CAFFEINE 65 mg ORAL TAB...,PANADOL Extra
48,1049632,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg ORAL TABLE...,Benadryl Allergy Ultratab
49,1550957,DIPHENHYDRAMINE HYDROCHLORIDE 25 mg / NAPROXEN...,NAPROXEN SODIUM PM
50,2670598,DEXTROMETHORPHAN HYDROBROMIDE 20 mg in 5 g / A...,Vicks DayQuil HOT REMEDY Cold and Flu
51,1659175,ACETAMINOPHEN 500 mg / DIPHENHYDRAMINE HYDROCH...,Theraflu Severe Cold relief Nighttime

In [38]:
def Fetch_Ingredients(ID):
    query = f"""
    SELECT c.STR as Full_String
    FROM RXNCONSO c
    JOIN RXNREL r
        ON c.RXCUI = r.RXCUI2
    WHERE r.RXCUI1 = "{ID}"
      AND c.TTY = "SCDC"
    GROUP BY Full_String;
    """

    df = pd.read_sql(query, engine)

    results = []

    for text in df["Full_String"]:
        match = re.match(r"(.+?)\s+(\d+)\s+MG", text)
        if match:
            ingredient = match.group(1)
            concentration = float(match.group(2))
            results.append({
                "Ingredient": ingredient,
                "Concentration": concentration
            })

    return results

In [39]:
def Fetch_Heatmap(df, drug_of_interest_id, drug_of_interest_name):

    searched_row = pd.DataFrame({
        "ID": [str(drug_of_interest_id)],
        "Product_Name": [drug_of_interest_name]
    })

    df_extended = pd.concat(
        [searched_row, df[["ID", "Product_Name"]].copy()],
        ignore_index=True
    )

    # ensure string IDs
    df_extended["ID"] = df_extended["ID"].astype(str)

    # ---- 1) Get all ingredient rows in ONE query ----
    ids = df_extended["ID"].dropna().unique().tolist()
    if len(ids) == 0:
        return pd.DataFrame(columns=["Product_Name", "ID", "Ingredients_List", "Dose_Form"])

    placeholders = ", ".join([f":id{i}" for i in range(len(ids))])
    params = {f"id{i}": ids[i] for i in range(len(ids))}

    sql_ing = text(f"""
        SELECT
            r.RXCUI1 AS ID,
            c.STR    AS Ingredient,
            -- If you have a concentration column elsewhere, join it here.
            -- For now, keep a placeholder concentration = 1 if present, else 0 won't appear anyway.
            1.0 AS Concentration
        FROM RXNREL r
        JOIN RXNCONSO c
            ON c.RXCUI = r.RXCUI2
        WHERE r.RXCUI1 IN ({placeholders})
          AND c.TTY = 'SCDC'
    """)

    long_df = pd.read_sql(sql_ing, engine, params=params)

    # If you truly have concentrations, replace the query above to bring the real concentration.
    # Then keep this numeric cleanup:
    long_df["Concentration"] = pd.to_numeric(long_df["Concentration"], errors="coerce").fillna(0)

    if long_df.empty:
        out = df_extended.drop_duplicates("Product_Name")[["Product_Name", "ID"]].copy()
        out["Ingredients_List"] = [[] for _ in range(len(out))]
        out["Dose_Form"] = None
        return out.reset_index(drop=True)

    long_df = long_df.merge(df_extended[["ID", "Product_Name"]], on="ID", how="left")

    # ---- 2) Pivot ----
    heatmap_wide = (
        long_df.pivot_table(
            index="Product_Name",
            columns="Ingredient",
            values="Concentration",
            aggfunc="max",
            fill_value=0
        )
        .reset_index()
    )

    ingredient_list_df = (
        long_df.groupby("Product_Name")["Ingredient"]
        .apply(lambda s: sorted(set(s)))
        .reset_index(name="Ingredients_List")
    )

    id_df = (
        df_extended[["Product_Name", "ID"]]
        .drop_duplicates(subset=["Product_Name"], keep="first")
        .reset_index(drop=True)
    )

    heatmap_df = (
        heatmap_wide
        .merge(ingredient_list_df, on="Product_Name", how="left")
        .merge(id_df, on="Product_Name", how="left")
    )

    heatmap_df["Dose_Form"] = None 

    return heatmap_df

In [40]:
heatmap_df = Fetch_Heatmap(df2,ID,Name)
heatmap_df

,Product_Name,acetaminophen 325 MG,acetaminophen 500 MG,acetaminophen 650 MG,aspirin 500 MG,caffeine 60 MG,caffeine 65 MG,chlorpheniramine maleate 2 MG,dexbrompheniramine maleate 1 MG,dextromethorphan hydrobromide 15 MG,...,ibuprofen 200 MG,naproxen sodium 220 MG,pamabrom 25 MG,phenylephrine hydrochloride 10 MG,phenylephrine hydrochloride 5 MG,pseudoephedrine hydrochloride 30 MG,pyrilamine maleate 15 MG,Ingredients_List,ID,Dose_Form
0,ADVIL PM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,"[diphenhydramine hydrochloride 25 MG, ibuprofe...",901814,None
1,Adult Allergy Relief,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],2046528,None
2,Aleve PM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,"[diphenhydramine hydrochloride 25 MG, naproxen...",1550963,None
3,Allergy Plus Congestion Relief,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[diphenhydramine hydrochloride 25 MG, phenylep...",1052928,None
4,Assured Headache PM (Aspirin Free),0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, diphenhydramine citrate...",1099872,None
5,BC MAX,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, aspirin 500 MG, caffein...",2360605,None
6,Banophen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1092421,None
7,Benadryl Allergy Liqui-Gels,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1049910,None
8,Benadryl Allergy Plus Congestion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[diphenhydramine hydrochloride 25 MG, phenylep...",1926221,None
9,Benadryl Allergy Ultratab,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1049632,None
10,Biogesic,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, dexbrompheniramine male...",1798453,None
11,Buscapina,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[acetaminophen 500 MG, caffeine 60 MG, pyrilam...",1597298,None
12,CETAFEN EXTRA,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],1358835,None
13,CONTAC Cold Flu Night,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"[acetaminophen 500 MG, chlorpheniramine maleat...",1052679,None
14,Coricidin HBP Night,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, chlorpheniramine maleat...",1098496,None
15,DG HEALTH MULTI SYMPTOM SEVERE COLD,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[acetaminophen 500 MG, dextromethorphan hydrob...",1189316,None
16,Dormin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1919073,None
17,EXTRA STRENGTH TYLENOL SEVERE COUGH PLUS SORE ...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, dextromethorphan hydrob...",247324,None
18,Excedrin Tension Headache,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, caffeine 65 MG]",404172,None
19,Extra Strength Mapap,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],209443,None
20,Extra Strength TYLENOL Cold Plus Flu Multi-Act...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,"[acetaminophen 500 MG, dextromethorphan hydrob...",1250743,None
21,Extra Strength TYLENOL Cold plus Flu Multi-Act...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,"[acetaminophen 500 MG, chlorpheniramine maleat...",1089968,None
22,GOODYS PM,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, diphenhydramine citrate...",1297947,None
23,Green Guard Advanced Sinus Relief,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"[acetaminophen 500 MG, phenylephrine hydrochlo...",1101534,None
24,MAPAP Extra Strength,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],209890,None
25,NAPROXEN SODIUM PM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,"[diphenhydramine hydrochloride 25 MG, naproxen...",1550957,None
26,NIGHTTIME SLEEP AID,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1049909,None
27,Nytol,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1092416,None
28,PANADOL Extra,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, caffeine 65 MG]",1872075,None
29,PANADOL Extra Strength,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],200977,None
30,Pamprin Multi-Symptom Maximum Strength,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,"[acetaminophen 500 MG, pamabrom 25 MG, pyrilam...",1053852,None
31,Pharbetol,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],1293942,None
32,Premsyn pms Premenstrual Pain Relief,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,"[acetaminophen 500 MG, pamabrom 25 MG, pyrilam...",1052641,None
33,Rapidol,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],198439,None
34,SEVERE COLD plus FLU DAYTIME,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[acetaminophen 500 MG, dextromethorphan hydrob...",1550968,None
35,Severe Allergy Plus Sinus Headache,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"[acetaminophen 325 MG, diphenhydramine hydroch...",1046751,None
36,Simply Sleep,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1092466,None
37,Sominex,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1086986,None
38,TYLENOL Extra Strength,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],2374361,None
39,Tension Headache,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, caffeine 65 MG]",307686,None
40,Theraflu Severe Cold relief Nighttime,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[acetaminophen 500 MG, diphenhydramine hydroch...",1659175,None
41,Tylenol Extra Strength Caplet,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],209459,None
42,Tylenol PM Extra Strength,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, diphenhydramine hydroch...",1092378,None
43,Unisom SleepMelts Nighttime Sleep-Aid,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1093102,None
44,Unisom SleepMinis Nighttime Sleep-Aid,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1648369,None
45,VALUMEDS ALLERGY RELIEF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1049630,None
46,VALUMEDS EXTRA STRENGTH PAIN RELIEF,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[acetaminophen 500 MG],198440,None
47,Vicks DayQuil HOT REMEDY Cold and Flu,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 500 MG, dextromethorphan hydrob...",2670598,None
48,Vicks NyQuil HOT REMEDY Cold and Flu,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[acetaminophen 650 MG, diphenhydramine hydroch...",2670677,None
49,Wal-Som,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1437725,None
50,ZzzQuil Nighttime Sleep-Aid,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[diphenhydramine hydrochloride 25 MG],1248360,None
51,menstrual pain relief maximum strength,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,"[acetaminophen 500 MG, pamabrom 25 MG, pyrilam...",1052637,None
52,nighttime severe cold and cough,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[acetaminophen 650 MG, diphenhydramine hydroch...",1659960,None

In [41]:
def Create_Altair_Heatmap(heatmap_df, drug_of_interest_name):
    if "Product_Name" not in heatmap_df.columns:
        heatmap_df = heatmap_df.reset_index()

    num_products = heatmap_df["Product_Name"].nunique()
    height_per_product = 20
    dynamic_height = max(250, min(1400, num_products * height_per_product))

    non_ingredient_cols = {"Product_Name", "Ingredients_List", "ID", "Dose_Form"}
    value_cols = [c for c in heatmap_df.columns if c not in non_ingredient_cols]

    df_long = heatmap_df.melt(
        id_vars=["Product_Name"],
        value_vars=value_cols,
        var_name="Ingredient",
        value_name="Concentration"
    )

    df_long["Product_Name"] = df_long["Product_Name"].astype(str)
    df_long["Ingredient"] = df_long["Ingredient"].astype(str)
    df_long["Concentration"] = pd.to_numeric(df_long["Concentration"], errors="coerce").fillna(0)

    df_long["Relative_Conc"] = (
        df_long.groupby("Ingredient")["Concentration"]
        .transform(lambda x: x / x.max() if x.max() != 0 else 0)
    )

    ingredients = sorted(df_long["Ingredient"].unique())
    if len(ingredients) == 0:
        return alt.Chart(pd.DataFrame({"msg": ["No data to plot."]})).mark_text().encode(text="msg:N")

    first_ing = ingredients[0]
    last_ing = ingredients[-1]

    df_rows = (
        df_long[["Product_Name"]]
        .drop_duplicates()
        .sort_values("Product_Name")
        .reset_index(drop=True)
    )
    df_rows["row_index"] = df_rows.index
    df_rows["is_odd"] = (df_rows["row_index"] % 2 == 1)
    df_rows["x_start"] = first_ing
    df_rows["x_end"] = last_ing

    # Shared encodings
    base = alt.Chart(df_long).encode(
    x=alt.X(
        "Ingredient:N",
        axis=alt.Axis(labelAngle=-45),
        sort=ingredients,
        scale=alt.Scale(padding=0) 
    ),
    y=alt.Y("Product_Name:N", sort='-x')
)

    row_bands = alt.Chart(df_rows).mark_rect().encode(
    x=alt.X(
        "x_start:N",
        sort=ingredients,
        scale=alt.Scale(padding=0), 
        title=None
    ),
    x2="x_end:N",
    y=alt.Y("Product_Name:N", sort='-x'),
    color=alt.condition(
        alt.datum.is_odd,
        alt.value("#efe7f6"),
        alt.value("#f6f3ef")
    )
)
    # 1) Highlight zero cells ONLY for drug_of_interest row
    highlight_zeros = base.transform_filter(
        (alt.datum.Product_Name == str(drug_of_interest_name)) &
        (alt.datum.Concentration == 0)
    ).mark_rect().encode(
        color=alt.value("#f3d7d7")
    )

    # 2) Main heatmap: non-zero cells only
    nonzero_layer = base.transform_filter(
        alt.datum.Concentration > 0
    ).mark_rect().encode(
        color=alt.Color(
            "Relative_Conc:Q",
            scale=alt.Scale(scheme="reds", domain=[0, 1]),
            title="Relative Concentration"
        ),
        tooltip=[
            "Product_Name:N",
            "Ingredient:N",
            alt.Tooltip("Concentration:Q", title="Concentration (mg)"),
            alt.Tooltip("Relative_Conc:Q", format=".2f", title="Relative")
        ]
    )

    chart = (row_bands + highlight_zeros + nonzero_layer).properties(
        width=700,
        height=dynamic_height,
        title=f"Ingredient Concentration Heatmap (zebra rows + 0-cells highlighted for: {drug_of_interest_name})"
    ).configure_view(
        fill="#f6f3ef",
        strokeOpacity=0
    ).configure(
        background="#f6f3ef"
    )

    return chart

In [45]:
Create_Altair_Heatmap(heatmap_df,Name)

alt.LayerChart(...)

## Clustering

In [46]:
def Create_UMAP_Cluster(heatmap_df, drug_of_interest_name, doseform_weight=2.0, jitter_strength=0.15):

    # ---- 0) Hard checks ----
    if heatmap_df is None:
        raise ValueError("heatmap_df is None")
    if heatmap_df.empty:
        raise ValueError("heatmap_df is EMPTY (0 rows). UMAP can't run.")

    ignore_cols = {"Product_Name", "Ingredients_List", "ID", "Dose_Form"}
    ingredient_cols = [c for c in heatmap_df.columns if c not in ignore_cols]

    # Dose form one-hot
    df_form = heatmap_df[["Dose_Form"]].copy()
    df_form["Dose_Form"] = df_form["Dose_Form"].fillna("UNKNOWN").astype(str)
    form_ohe = pd.get_dummies(df_form["Dose_Form"], prefix="DF").astype(float) * float(doseform_weight)

    # Ingredient features
    if len(ingredient_cols) > 0:
        X_ing = (
            heatmap_df[ingredient_cols]
            .apply(pd.to_numeric, errors="coerce")
            .fillna(0)
            .to_numpy(dtype=float)
        )
    else:
        # No ingredient columns → (n,0)
        X_ing = np.zeros((len(heatmap_df), 0), dtype=float)

    # Combine
    X = np.hstack([X_ing, form_ohe.to_numpy(dtype=float)])

    # Diagnostics (super important)
    n_samples, n_features = X.shape
    print(f"DEBUG: n_samples={n_samples}, n_features={n_features}, ingredient_cols={len(ingredient_cols)}, doseform_cols={form_ohe.shape[1]}")
    print("DEBUG: unique products =", heatmap_df["Product_Name"].nunique())

    # If you end up with 0 rows or only 1 row, UMAP will fail
    if n_samples < 2:
        raise ValueError(f"UMAP needs at least 2 rows. You have {n_samples}. Your heatmap_df likely contains only '{drug_of_interest_name}'.")

    # UMAP requires n_neighbors < n_samples
    n_neighbors = min(10, n_samples - 1)
    n_neighbors = max(2, n_neighbors)

    reducer = umap.UMAP(
        n_neighbors=n_neighbors,
        min_dist=0.3,
        n_components=2,
        metric="euclidean",
        random_state=42
    )
    embedding = reducer.fit_transform(X)

    plot_df = heatmap_df[["Product_Name", "Ingredients_List", "Dose_Form"]].copy()
    plot_df["UMAP1"] = embedding[:, 0]
    plot_df["UMAP2"] = embedding[:, 1]

    plot_df["Ingredients_Str"] = plot_df["Ingredients_List"].apply(
        lambda x: ", ".join(x) if isinstance(x, list) else str(x)
    )

    plot_df["Is_Interest"] = plot_df["Product_Name"].astype(str).str.lower().eq(str(drug_of_interest_name).lower())

    rng = np.random.default_rng(42)
    plot_df["UMAP1_jitter"] = plot_df["UMAP1"] + rng.normal(0, jitter_strength, len(plot_df))
    plot_df["UMAP2_jitter"] = plot_df["UMAP2"] + rng.normal(0, jitter_strength, len(plot_df))

    chart = alt.Chart(plot_df).mark_circle(size=100).encode(
        x=alt.X("UMAP1_jitter:Q", title="UMAP Dimension 1"),
        y=alt.Y("UMAP2_jitter:Q", title="UMAP Dimension 2"),
        color=alt.condition(alt.datum.Is_Interest, alt.value("red"), alt.value("steelblue")),
        size=alt.condition(alt.datum.Is_Interest, alt.value(220), alt.value(80)),
        tooltip=[
            alt.Tooltip("Product_Name:N", title="Product"),
            alt.Tooltip("Dose_Form:N", title="Dose Form"),
            alt.Tooltip("Ingredients_Str:N", title="Ingredients")
        ]
    ).properties(
        width=650,
        height=550,
        title=f"Drug Similarity Clustering (UMAP) — DoseForm weighted x{doseform_weight}"
    )

    return chart

In [47]:
Create_UMAP_Cluster(heatmap_df, Name)

DEBUG: n_samples=53, n_features=21, ingredient_cols=20, doseform_cols=1
DEBUG: unique products = 53

C:\Users\ckart\miniconda3\envs\dsenv\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

alt.Chart(...)

## Frequncy Chart

In [48]:
def Create_Ingredient_Frequency_Bar(heatmap_df):

    # Identify ingredient columns
    ignore_cols = {"Product_Name", "Ingredients_List", "ID", "Dose_Form"}
    ingredient_cols = [c for c in heatmap_df.columns if c not in ignore_cols]

    # Convert to binary presence matrix
    binary_df = heatmap_df[ingredient_cols].gt(0)

    # Count frequency
    freq_series = binary_df.sum().sort_values(ascending=False)

    # Convert to dataframe
    freq_df = freq_series.reset_index()
    freq_df.columns = ["Ingredient", "Product_Count"]

    # Create bar chart
    chart = alt.Chart(freq_df).mark_bar().encode(

        x=alt.X(
            "Product_Count:Q",
            title="Number of Products"
        ),

        y=alt.Y(
            "Ingredient:N",
            sort='-x',
            title="Ingredient"
        ),

        color=alt.Color(
            "Product_Count:Q",
            scale=alt.Scale(scheme="reds"),
            title="Frequency"
        ),

        tooltip=[
            alt.Tooltip("Ingredient:N"),
            alt.Tooltip("Product_Count:Q", title="Products containing ingredient")
        ]

    ).properties(
        width=650,
        height=400,
        title="Ingredient Frequency Across Products"
    )

    return chart

In [49]:
Create_Ingredient_Frequency_Bar(heatmap_df)

alt.Chart(...)